# Generated by Django 4.1 on 2022-11-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_room_name_alter_message_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
